#!/bin/sh
if test "x${NRNHOME}" = "x" ; then
    NRNHOME="/home/pbczgf/nrn/conda/envs/py36/lib/python3.6/site-packages/neuron/.data"
fi
if test "${NEURONHOME}" = "" ; then
    NEURONHOME=${NRNHOME}/share/nrn
    export NEURONHOME
fi
if test "x${NRNBIN}" = "x" ; then
    NRNBIN="/home/pbczgf/nrn/conda/envs/py36/bin"
fi
if test "" = "yes" ; then
    NRNIV="${NRNBIN}/nrniv.app/Contents/MacOS/nrniv"
else
    NRNIV="${NRNBIN}/nrniv"
fi
"${NRNIV}" -dll "/home/pbczgf/NeuroResearch/cells/CA3Cell_Izh/x86_64/.libs/libnrnmech.so" "$@"
